module.exports = {
  apps: [
    {
      name: "smart-match-api",
      script: "src/app.js",
      instances: "max",
      exec_mode: "cluster",
      max_memory_restart: "2G",
      node_args: [
        "--max-old-space-size=1536",
        "--optimize-for-size",
        "--max-http-header-size=8192",
        "--gc-interval=200",
      ],
      env: {
        NODE_ENV: "production",
        PORT: 8080,
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 8080,
      },
      log_type: "json",
      merge_logs: true,
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      out_file: "logs/pm2-out.log",
      error_file: "logs/pm2-error.log",
      log_file: "logs/pm2-combined.log",
      max_size: "50M",
      retain: 10,
      compress: true,
      rotate_interval: "0 0 * * *",
      health_check_http: "http://localhost:8080/api/health",
      health_check_grace_period: 3000,
      max_restarts: 15,
      min_uptime: "30s",
      restart_delay: 1000,
      exp_backoff_restart_delay: 100,
      watch: false,
      ignore_watch: ["node_modules", "logs", "uploads", ".git"],
      source_map_support: false,
      instance_var: "INSTANCE_ID",
      combine_logs: true,
      vizion: false,
    },
  ],
}
